version: '3.7'

x-app-common: &app-common
  image: biocondabot
  networks:
    - backend
  environment:
    - PYTHONUNBUFFERED=true
    - APP_KEY_FILE=/run/secrets/app_key
    - APP_ID_FILE=/run/secrets/app_id
    - CODE_SIGNING_KEY_FILE=/run/secrets/code_sign_key
    - CLOUDAMQP_URL=amqp://mq:5672
  secrets:
    - app_key
    - app_id
    - code_sign_key
  depends_on:
    - mq

services:
  mq:
    hostname: mq    
    image: rabbitmq:latest
    secrets:
      - source: erlang_cookie
        target: /var/lib/rabbitmq/.erlang.cookie
        uid: '999'
        gid: '999'
        mode: 0600
    user: rabbitmq
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - backend
  
  web:
    <<: *app-common
    hostname: web
    build:
      context: ..
      dockerfile: Dockerfile.web
    command: >-
       gunicorn 
       --worker-class aiohttp.worker.GunicornWebWorker
       --bind 0.0.0.0:80
       bioconda_utils.bot:init_app
       #(disable_internal_celery=True)
       //ports:
         //- "80:80"
    expose: [80]
    depends_on:
      - mq

  worker:
    <<: *app-common
    command: >-
      celery worker
      -l info
      -A bioconda_utils.bot
      --without-heartbeat
    deploy:
      mode: replicated
      replicas: 2

  shepherd:
    image: mazzolino/shepherd:0.3.0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      placement:
        constraints:
        - node.role == manager

  flower:
    image: mher/flower
    command: >-
      flower
      --broker=amqp://mq:5672
      --port=8888
    ports:  
      - 8888:8888
    networks:
      - backend
      
networks:
  backend:

secrets:
  app_id:
    file: secrets/app_id.txt
  app_key:
    file: secrets/app_key.pem
  code_sign_key:
    file: secrets/code_sign_key.asc
  erlang_cookie:
    file: secrets/erlang_cookie.txt

volumes:
  rabbitmq-data:

