# Additional bioconda-specific pinnings to use in addition to those specified
# in
# https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/master/recipe/conda_build_config.yaml

c_compiler:
  # new compilers
  - gcc                        # [linux                               and (environ.get('CF_COMPILER_STACK') == 'comp7')]
  - clang                      # [osx                                 and (environ.get('CF_COMPILER_STACK') == 'comp7')]
cxx_compiler:
  # new compilers
  - gxx                        # [linux                               and (environ.get('CF_COMPILER_STACK') == 'comp7')]
  - clangxx                    # [osx                                 and (environ.get('CF_COMPILER_STACK') == 'comp7')]
fortran_compiler:              # [unix or win64]
  - gfortran                   # [(linux or osx)                      and (environ.get('CF_COMPILER_STACK') == 'comp7')]

pin_run_as_build:
  htslib:
    max_pin: x.x
  bamtools:
    max_pin: x.x.x
  libdeflate:
    max_pin: x.x

htslib:
  - 1.9
bamtools:
  - 2.4.1
libdeflate:
  - 1.0
r_base:
  - 3.5.1
