# Additional bioconda-specific pinnings to use in addition to those specified
# in
# https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/master/recipe/conda_build_config.yaml

c_compiler:
  # new compilers
  - gcc                        # [linux                               and (environ.get('CF_COMPILER_STACK') == 'comp7')]
  - clang                      # [osx                                 and (environ.get('CF_COMPILER_STACK') == 'comp7')]
cxx_compiler:
  # new compilers
  - gxx                        # [linux                               and (environ.get('CF_COMPILER_STACK') == 'comp7')]
  - clangxx                    # [osx                                 and (environ.get('CF_COMPILER_STACK') == 'comp7')]
fortran_compiler:              # [unix or win64]
  - gfortran                   # [(linux or osx)                      and (environ.get('CF_COMPILER_STACK') == 'comp7')]

zip_keys:
  # Dual compiler zip
  -                             # [                                       (environ.get('CF_COMPILER_STACK') == 'comp7')]
    - c_compiler                # [(linux or osx)                     and (environ.get('CF_COMPILER_STACK') == 'comp7')]
    - cxx_compiler              # [(linux or osx)                     and (environ.get('CF_COMPILER_STACK') == 'comp7')]
    - fortran_compiler          # [(linux or osx)                     and (environ.get('CF_COMPILER_STACK') == 'comp7')]
    - channel_sources           # [(linux or osx)                     and (environ.get('CF_COMPILER_STACK') == 'comp7')]
    - channel_targets           # [(linux or osx)                     and (environ.get('CF_COMPILER_STACK') == 'comp7')]
    - docker_image              # [linux                              and (environ.get('CF_COMPILER_STACK') == 'comp7')]
    - build_number_decrement    # [(linux or osx)                     and (environ.get('CF_COMPILER_STACK') == 'comp7')]


pin_run_as_build:
  htslib:
    max_pin: x.x
  bamtools:
    max_pin: x.x.x
  libdeflate:
    max_pin: x.x

htslib:
  - 1.9
bamtools:
  - 2.4.1
libdeflate:
  - 1.0
r_base:
  - 3.5.1
