type: object
properties:
    env_matrix:
        type: string
    blacklists:
        type: array
    docker_image:
        type: string
    upload_channel:
        type: string
    channels:
        type: array
    conda_build_version:
        type: string
