env_matrix: ../scripts/env_matrix.yml
blacklists:
  - r-blacklist
upload_channel: bioconda
channels:
  - anaconda
  - r
  - bioconda
#setup:
#  - pip install git+https://github.com/bioconda/conda-build.git@reintroduce-skip-existing
