env_matrix: example_env_matrix.yml
requirements: requirements.txt
blacklists:
    - r-blacklist
docker_image: "condaforge/linux-anvil"
docker_url: 'unix://var/run/docker.sock'
channels:
    - r
    - bioconda
    - defaults
